services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: event_booking
      JWT_SECRET: your_jwt_secret


  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: event_booking
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Persists database data across restarts

volumes:
  db_data:
